### ISSUE TITLE
Bounty Board - Onboarding to Sifchain Graphic

### ISSUE THREAD

**Issue by sifmoon** [Sifchain/The-Bounty-Board#2]
**Summary:**
- We want user's onboarding experience into Sifchain to be extremely easy. DEXs can be intimidating and the average user can easily get lost. 
- We should create a 1-pager that walks a user through a 'Welcome to Sifchain!' journey to get them started in the DEX and lets them know what to do, why to do it, and how to do it. Basically walk them through the steps of onboarding as a user, while educating them along the way.
- The final form of this should be in a PDF.

**Requirements:**
- We need to make a 'onboarding to Sifchain' that will be posted everywhere: discord, reddit, telegram, docs site. We need to make sure that no matter where users go, they can find the onboarding info easily and cleanly.
- It should highlight the onboarding process in an easy to follow and understand way. This includes the below tasks. I have added some commentary that can be used/adjusted as you see fit:
1. Download and set up your wallets (Keplr/CosmoStation) and MetaMask. Provide a brief 1-2 liner on why a user has to do setup wallets, and why they need both. 
Import: 'Import another token into Sifchain! You can import any token you see in the 'balances' tab. Yes, this is ALOT of options. You can choose a token from any of our connected chains (Cosmos, Ethereum, Polygon, Avalanche, etc. How cool is that? You can use Sifchain to import ANY of these tokens into our DEX and use those tokens to swap for any other token. We are actually the first, and only, DEX that allows you to do this. We are your 1-stop shop to swap and pool across many of these assets. Not only this, but we are actively working on building in even more connections to other chains. This will mean that you can use Sifchain to swap ANY asset you own for ANY other asset at a very low cost.' Reward: 5 Rowan
2. Get Rowan: Swap for ROWAN! Now that you have an amount of another token in the DEX, you will want to swap for some ROWAN. This is a way to ensure you can use the other areas of the DEX (like add to a liquidity pool and delegate). Go ahead and swap some of the non-ROWAN token you have for ROWAN. The swap transaction will be extremely quick & cheap. Gas fees are very low (especially compared to Ethereum). You will need to pay a small swap fee that is paid to the Liquidity Providers for funding the pools to enable you to execute this swap. You will learn more about this process in the next step.
3. Pool: 'Pool your tokens! Now, you'll want to add liquidity to any of our Pools. Why would you do this? Well, you can earn some pretty stellar rewards by doing so. Check out the Pool APY to see the rate of return you can earn from providing liquidity. Not only can you earn additional rewards from various Liquidity Mining programs, but you will earn fees from users who swap against this pool. As you saw in step 2, when users execute swaps, they pay a liquidity provider fee. Now that you are a liquidity provider (or LP), this is your way of earning those fees. Add liquidity to any of those pools! 
4. Stake: Delegate your ROWAN! Now take some of your ROWAN and delegate it to a node operator. Delegating to a node operator helps secure the network, and takes a very little amount of effort from you. Node Operators are trusted in processing transactions and ensuring the network is operational and safe. You can choose any of the node operators and delegate your ROWAN to them as a sign of support to their node. Node Operators earn rewards by processing transactions in the network. Every node sets a commission rate that is paid to their delegators. This means that if their commission rate is 10%, this means that for every reward that your delegation earns for them, you will take 90% of it and they will take 10%. Go ahead and delegate, sit back, and earn rewards based on your support. Just how much can you earn? Check out the APY within the Keplr Wallet or Keplr dashboard (hint: its a lot). 
- This should be a visually appealing graphic that invites users in, and makes them want to read everything. 

**RFP Submission Criteria:**
- RFP eligibility dates: May 2nd - open ended. 
- RFP Requirements: 
     - Post a comment on this ticket with the following outlined:
          - Describe your solution
          - What it will look like
          - How you will go about creating it
          - Previous examples of your work
          - If it needs updating in the future, can that be done easily? If yes, how/why.

**Payout:**
- 3,500 ROWAN
- RFP, 1 proposal will be chosen by SifCore team after RFP eligibility dates.

**Comment by sartinosa** [comment]
Describe your solution: Made an infographic that describes how to start on Sifchain. Touch of gold on the whole infographic. I also already made a sample of what it looks like. Attached are some of my previous works. I have the softcopy that can be edited anytime
Samples:
![Crescent Infog 2](https://user-images.githubusercontent.com/104910899/166693673-b223ae62-3325-4e08-b71c-4c765173814a.png)
![evmos infog 3](https://user-images.githubusercontent.com/104910899/166693725-edc1fefe-ebab-4e2e-aad3-d82ae7c96891.png)
Onboarding Guide Sample:
![Onboarding](https://user-images.githubusercontent.com/104910899/166693967-abc3bdb5-6868-44c9-bd41-b3ad153a9c76.png)
pdf file readily available. attached png file for smaller file size

**Comment by sifmoon** [comment]
@sartinosa thank you for your proposal! Just some overall feedback on this:
- Are you able to work with a designer to bring some more cleanliness to the overall aesthetics of it? I am not a designer by any means but initial recommendations would be:
     - The entire color scheme needs to be adjusted. 
     - The fonts should be adjusted as well.
     - It should look 'cleaner' and 'crisper'
     - We are currently undergoing a brand upgrade and a key component of it is that our user base is more technically advanced and that is the crowd we should be talking to with our design assets. This may help you in doing some adjusting of the overall look & feel of this.

**Comment by sifmoon** [comment]
Update: going to leave this RFP open-ended for now.

**Comment by sartinosa** [comment]
Hi Sifmoon,

Sorry for the late reply. Was preoccupied by my day job. Unfortunately,
there are no designers that I can get in touch with. Will try to revise the
proposal based on your feedback. Will be sending it to discord if it's
alright with you so as to not flood the github if there are other revisions
needed.

Thanks and Regards,
Byron

**Comment by merkletreeibc** [comment]
Closing as this is no longer needed
