### ISSUE TITLE
Bounty Board - Animated video describing PMTP in 1-2 minutes 

### ISSUE THREAD

**Issue by sifmoon** [Sifchain/The-Bounty-Board#4]
**Goal:**
- Create a video that takes a seemingly complex process (PMTP) and create an animated video to make it very easy to understand.

**Requirements:**
- Content Creation Starter Pack: https://www.notion.so/sifchain/Content-Creator-Guidelines-031c93f1258149e79d3478a9f6d21009
- PMTP Info: https://docs.sifchain.finance/project/about-sifchain/roadmap/pmtp
- Brief for video: https://docs.google.com/document/d/1Mm2dXZfn42nbRaY2RzbXxt1G3KtGXD5pLqBnYKbjSTQ/edit

**Execution:**
- The individual/s doing this video should provide a story-board concept of the video and the storyline of it and get sign-off from SifCore before moving on to final video creation.

**Definition of Done:**
- A fully complete video that follows the above briefing, and agreed upon RFP. 

**RFP Submission Criteria:**
- RFP eligibility dates: April 25th - open ended.
- RFP Requirements:
     - Post a comment on this ticket with the following outlined:
          - Describe your video
          - Provide examples of previous videos you have created
          - Provide a story-board & outline of the video 
          - If you can do different looks/feels, provide these options so Sifcore can understand the flexibility/options we have to move forward with. 

**Estimated payout:**
- ~25,000-30,000 ROWAN
- RFP, 1 proposal will be chosen by SifCore team after RFP eligibility dates.

**Comment by BobTomazic** [comment]
I'm Bob. I'm am a Cosmonaut, with a "day job" as a talent agent. I represent nearly 100 Voice Actors that are fantastic at narrating this type of video. I would be very happy to offer my services to provide narrations to this video for a very low cost (5-7% of total payout, payable in ROWAN, or any IBC coin). You provide a script, choose a voice from my library, and I'll send you a WAV file 48 hrs later that you can drop right into your editing software.  Please feel free to contact me with further questions or requests. I'd love to be involved with this project.  booking@ztagency.com 
I apologize if this type of post isn't allowed here. I'd be happy to go through any other channel to offer this service, or package a "Voiceovers for Videos" one-sheet, to go into the Content Creator Lunchbox.

**Comment by sifmoon** [comment]
Hi @BobTomazic ! Thanks for reaching out. This is something to keep in mind for other people that would be interested in doing the animation piece of this. It looks like you would help them after they do the animated piece, right?

**Comment by BobTomazic** [comment]
Thanks for responding. 
Generally, the process is 1. Write the script, 2. Record the narration, 3. Create the animation based on the audio narration. Due to timing/pacing, it much easier to animate to the voice track, than to try to add a voice afterwards. I'm definitely looking to partner with some animators to work on projects like this.

**Comment by sifmoon** [comment]
Update: No one submitted a proposal for this so I will leave it here and anyone wanting to submit a proposal in the future may do so.

**Comment by merkletreeibc** [comment]
Closing as it is no longer needed.
